echo \" <<'RUN_AS_BATCH' >/dev/null ">NUL "\" \`" <#"
@ECHO OFF
REM LICENSE CLAUSES HERE
REM ----------------------------------------------------------------------------




REM ############################################################################
REM # Windows BATCH Codes                                                      #
REM ############################################################################
where /q powershell
if errorlevel 1 (
        echo "ERROR: missing powershell facility."
        exit /b 1
)

copy /Y "%~nx0" "%~n0.ps1" >nul
timeout /t 1 /nobreak >nul
powershell -executionpolicy remotesigned -Command "& '.\%~n0.ps1' %*"
start /b "" cmd /c del "%~f0" & exit /b %errorcode%
REM ############################################################################
REM # Windows BATCH Codes                                                      #
REM ############################################################################
RUN_AS_BATCH
#> | Out-Null




echo \" <<'RUN_AS_POWERSHELL' >/dev/null # " | Out-Null
################################################################################
# Windows POWERSHELL Codes                                                     #
################################################################################
${env:hestiaKERNEL_ERROR_OK} = 0
${env:hestiaKERNEL_ERROR_BAD_EXEC} = 1
${env:hestiaKERNEL_ERROR_BAD_BUSY} = 2
${env:hestiaKERNEL_ERROR_BAD_DESCRIPTOR} = 3
${env:hestiaKERNEL_ERROR_BAD_EXCHANGE} = 4
${env:hestiaKERNEL_ERROR_BAD_MOUNT} = 5
${env:hestiaKERNEL_ERROR_BAD_PIPE} = 6
${env:hestiaKERNEL_ERROR_BAD_REQUEST} = 7
${env:hestiaKERNEL_ERROR_BAD_STREAM_PIPE} = 8
${env:hestiaKERNEL_ERROR_PROCESS_IS_DEAD} = 9
${env:hestiaKERNEL_ERROR_CANCELLED} = 10
${env:hestiaKERNEL_ERROR_CLEANING_REQUIRED} = 11
${env:hestiaKERNEL_ERROR_DEADLOCK} = 12
${env:hestiaKERNEL_ERROR_EXPIRED} = 13
${env:hestiaKERNEL_ERROR_ILLEGAL_BYTE_SEQUENCE} = 14
${env:hestiaKERNEL_ERROR_ILLEGAL_SEEK} = 15
${env:hestiaKERNEL_ERROR_INVALID_ARGUMENT} = 16
${env:hestiaKERNEL_ERROR_IS_EMPTY} = 17
${env:hestiaKERNEL_ERROR_MAXED_EXCHANGE} = 18
${env:hestiaKERNEL_ERROR_MAXED_QUOTA} = 19
${env:hestiaKERNEL_ERROR_MISSING_LOCK} = 20
${env:hestiaKERNEL_ERROR_IS_NOT_EMPTY} = 21
${env:hestiaKERNEL_ERROR_NOT_PERMITTED} = 22
${env:hestiaKERNEL_ERROR_NOT_POSSIBLE} = 23
${env:hestiaKERNEL_ERROR_NOT_POSSIBLE_BY_RFKILL} = 24
${env:hestiaKERNEL_ERROR_NOT_RECOVERABLE} = 25
${env:hestiaKERNEL_ERROR_OUT_OF_RANGE} = 26
${env:hestiaKERNEL_ERROR_PERMISSION_DENIED} = 27
${env:hestiaKERNEL_ERROR_TIMEOUT} = 28
${env:hestiaKERNEL_ERROR_TOO_MANY_READ} = 29
${env:hestiaKERNEL_ERROR_TOO_MANY_LOOP} = 30
${env:hestiaKERNEL_ERROR_TOO_MANY_REFERENCES} = 31
${env:hestiaKERNEL_ERROR_TOO_MANY_LINK} = 32
${env:hestiaKERNEL_ERROR_TOO_MANY_OPENED} = 33
${env:hestiaKERNEL_ERROR_TRY_AGAIN} = 34
${env:hestiaKERNEL_ERROR_UNSUPPORTED} = 35
${env:hestiaKERNEL_ERROR_WOULD_BLOCK} = 36




# lifecycle states
${env:hestiaKERNEL_ERROR_RESTART} = 37
${env:hestiaKERNEL_ERROR_RESUME} = 38
${env:hestiaKERNEL_ERROR_SHUTDOWN} = 39
${env:hestiaKERNEL_ERROR_SLEEP} = 40
${env:hestiaKERNEL_ERROR_STALLED} = 41
${env:hestiaKERNEL_ERROR_STANDBY} = 42
${env:hestiaKERNEL_ERROR_UNRESPONSIVE} = 43
${env:hestiaKERNEL_ERROR_TERMINATE} = 44
${env:hestiaKERNEL_ERROR_PROGRESS_SCHEDULED} = 45
${env:hestiaKERNEL_ERROR_PROGRESS_ALREADY_EXECUTING} = 46
${env:hestiaKERNEL_ERROR_PROGRESS_EXECUTING} = 47
${env:hestiaKERNEL_ERROR_PROGRESS_COMPLETED} = 48
${env:hestiaKERNEL_ERROR_PROGRESS_UNRESPONSIVE} = 49
${env:hestiaKERNEL_ERROR_PROGRESS_TERMINATE} = 50




# tri-tier inter-package communications
${env:hestiaKERNEL_ERROR_LV1_NOT_SYNC} = 51
${env:hestiaKERNEL_ERROR_LV1_PAUSED} = 52
${env:hestiaKERNEL_ERROR_LV1_RESET} = 53
${env:hestiaKERNEL_ERROR_LV2_NOT_SYNC} = 54
${env:hestiaKERNEL_ERROR_LV2_PAUSED} = 55
${env:hestiaKERNEL_ERROR_LV2_RESET} = 56
${env:hestiaKERNEL_ERROR_LV3_NOT_SYNC} = 57
${env:hestiaKERNEL_ERROR_LV3_PAUSED} = 58
${env:hestiaKERNEL_ERROR_LV3_RESET} = 59




# data (input/output parameters type etc)
${env:hestiaKERNEL_ERROR_DATA_BAD} = 60
${env:hestiaKERNEL_ERROR_DATA_EMPTY} = 61
${env:hestiaKERNEL_ERROR_DATA_INVALID} = 62
${env:hestiaKERNEL_ERROR_DATA_IS_UNIQUE} = 63
${env:hestiaKERNEL_ERROR_DATA_IS_NOT_UNIQUE} = 64
${env:hestiaKERNEL_ERROR_DATA_BUSY} = 65
${env:hestiaKERNEL_ERROR_DATA_DEAD} = 66
${env:hestiaKERNEL_ERROR_DATA_EXISTS} = 67
${env:hestiaKERNEL_ERROR_DATA_FAULTY} = 68
${env:hestiaKERNEL_ERROR_DATA_MISSING} = 69
${env:hestiaKERNEL_ERROR_DATA_OVERFLOW} = 70
${env:hestiaKERNEL_ERROR_DATA_POISONED} = 71
${env:hestiaKERNEL_ERROR_DATA_REMOVED} = 72
${env:hestiaKERNEL_ERROR_DATA_TOO_BIG} = 73
${env:hestiaKERNEL_ERROR_DATA_TOO_MANY_OPENED} = 74
${env:hestiaKERNEL_ERROR_DATA_TOO_LONG} = 75
${env:hestiaKERNEL_ERROR_DATA_MISMATCHED} = 76
${env:hestiaKERNEL_ERROR_DATA_IS_NOT_DIRECTORY} = 77
${env:hestiaKERNEL_ERROR_DATA_IS_NOT_FILE} = 78
${env:hestiaKERNEL_ERROR_DATA_IS_NOT_LINK} = 79
${env:hestiaKERNEL_ERROR_DATA_IS_NOT_SOCKET} = 80
${env:hestiaKERNEL_ERROR_DATA_REMOTE_CHANGED} = 81
${env:hestiaKERNEL_ERROR_DATA_REMOTE_ERROR} = 82
${env:hestiaKERNEL_ERROR_DATA_REMOTE_IO} = 83
${env:hestiaKERNEL_ERROR_DATA_MISSING_STREAMABLE_RESOURCES} = 84
${env:hestiaKERNEL_ERROR_DATA_NOT_STREAMABLE} = 85




# entity (device file directory object etc)
${env:hestiaKERNEL_ERROR_ENTITY_BAD} = 86
${env:hestiaKERNEL_ERROR_ENTITY_EMPTY} = 87
${env:hestiaKERNEL_ERROR_ENTITY_INVALID} = 88
${env:hestiaKERNEL_ERROR_ENTITY_IS_UNIQUE} = 89
${env:hestiaKERNEL_ERROR_ENTITY_IS_NOT_UNIQUE} = 90
${env:hestiaKERNEL_ERROR_ENTITY_BUSY} = 91
${env:hestiaKERNEL_ERROR_ENTITY_DEAD} = 92
${env:hestiaKERNEL_ERROR_ENTITY_EXISTS} = 93
${env:hestiaKERNEL_ERROR_ENTITY_FAULTY} = 94
${env:hestiaKERNEL_ERROR_ENTITY_MISSING} = 95
${env:hestiaKERNEL_ERROR_ENTITY_MISSING_CHILD} = 96
${env:hestiaKERNEL_ERROR_ENTITY_OUT_OF_BUFFER} = 97
${env:hestiaKERNEL_ERROR_ENTITY_POISONED} = 98
${env:hestiaKERNEL_ERROR_ENTITY_REMOVED} = 99
${env:hestiaKERNEL_ERROR_ENTITY_TOO_BIG} = 100
${env:hestiaKERNEL_ERROR_ENTITY_TOO_MANY_OPENED} = 101
${env:hestiaKERNEL_ERROR_ENTITY_UNATTACHED} = 102
${env:hestiaKERNEL_ERROR_ENTITY_MISMATCHED} = 103
${env:hestiaKERNEL_ERROR_ENTITY_IS_NOT_DIRECTORY} = 104
${env:hestiaKERNEL_ERROR_ENTITY_IS_NOT_FILE} = 105
${env:hestiaKERNEL_ERROR_ENTITY_IS_NOT_LINK} = 106
${env:hestiaKERNEL_ERROR_ENTITY_IS_NOT_SOCKET} = 107
${env:hestiaKERNEL_ERROR_ENTITY_REMOTE_CHANGED} = 108
${env:hestiaKERNEL_ERROR_ENTITY_REMOTE_ERROR} = 109
${env:hestiaKERNEL_ERROR_ENTITY_REMOTE_IO} = 110
${env:hestiaKERNEL_ERROR_ENTITY_MISSING_STREAMABLE_RESOURCES} = 111
${env:hestiaKERNEL_ERROR_ENTITY_NOT_STREAMABLE} = 112
${env:hestiaKERNEL_ERROR_ENTITY_STREAMABLE} = 113
${env:hestiaKERNEL_ERROR_ENTITY_A_TYPEWRITER} = 114
${env:hestiaKERNEL_ERROR_ENTITY_NOT_A_TYPEWRITER} = 115
${env:hestiaKERNEL_ERROR_ENTITY_BAD_DESCRIPTOR} = 116
${env:hestiaKERNEL_ERROR_ENTITY_FILETABLE_OVERFLOW} = 117




# key (cryptography)
${env:hestiaKERNEL_ERROR_KEY_BAD} = 118
${env:hestiaKERNEL_ERROR_KEY_DESTROYED} = 119
${env:hestiaKERNEL_ERROR_KEY_EXPIRED} = 120
${env:hestiaKERNEL_ERROR_KEY_MISSING} = 121
${env:hestiaKERNEL_ERROR_KEY_REJECTED} = 122
${env:hestiaKERNEL_ERROR_KEY_REVOKED} = 123




# library
${env:hestiaKERNEL_ERROR_LIBRARY_BAD} = 124
${env:hestiaKERNEL_ERROR_LIBRARY_CORRUPTED} = 125
${env:hestiaKERNEL_ERROR_LIBRARY_EXEC_FAILED} = 126
${env:hestiaKERNEL_ERROR_LIBRARY_MAXED} = 127
${env:hestiaKERNEL_ERROR_LIBRARY_MISSING} = 128




# network
${env:hestiaKERNEL_ERROR_NETWORK_BAD} = 129
${env:hestiaKERNEL_ERROR_NETWORK_BAD_AD} = 130
${env:hestiaKERNEL_ERROR_NETWORK_DOWN} = 131
${env:hestiaKERNEL_ERROR_NETWORK_NOT_CONNECTED} = 132
${env:hestiaKERNEL_ERROR_NETWORK_RESET} = 133
${env:hestiaKERNEL_ERROR_NETWORK_RFS} = 134
${env:hestiaKERNEL_ERROR_NETWORK_UNREACHABLE} = 135

${env:hestiaKERNEL_ERROR_NETWORK_HOST_DOWN} = 136
${env:hestiaKERNEL_ERROR_NETWORK_HOST_UNREACHABLE} = 137
${env:hestiaKERNEL_ERROR_NETWORK_SOCKET_UNSUPPORTED} = 138

${env:hestiaKERNEL_ERROR_NETWORK_ADDRESS_IN_USE} = 139
${env:hestiaKERNEL_ERROR_NETWORK_ADDRESS_UNAVAILABLE} = 140

${env:hestiaKERNEL_ERROR_NETWORK_CONN_ABORTED} = 141
${env:hestiaKERNEL_ERROR_NETWORK_CONN_IS_CONNECTED} = 142
${env:hestiaKERNEL_ERROR_NETWORK_CONN_MISSING_DEST_ADDRESS} = 143
${env:hestiaKERNEL_ERROR_NETWORK_CONN_MULTIHOP} = 144
${env:hestiaKERNEL_ERROR_NETWORK_CONN_NOT_CONNECTED} = 145
${env:hestiaKERNEL_ERROR_NETWORK_CONN_REFUSED} = 146
${env:hestiaKERNEL_ERROR_NETWORK_CONN_RESET} = 147

${env:hestiaKERNEL_ERROR_NETWORK_PAYLOAD_BAD} = 148
${env:hestiaKERNEL_ERROR_NETWORK_PAYLOAD_EMPTY} = 149
${env:hestiaKERNEL_ERROR_NETWORK_PAYLOAD_MISSING} = 150
${env:hestiaKERNEL_ERROR_NETWORK_PAYLOAD_TOO_LONG} = 151




# protocol
${env:hestiaKERNEL_ERROR_PROTOCOL_ADDRESS_UNSUPPORTED} = 152
${env:hestiaKERNEL_ERROR_PROTOCOL_BAD} = 153
${env:hestiaKERNEL_ERROR_PROTOCOL_FAMILY_UNSUPPORTED} = 154
${env:hestiaKERNEL_ERROR_PROTOCOL_MISSING} = 155
${env:hestiaKERNEL_ERROR_PROTOCOL_INVALID} = 156
${env:hestiaKERNEL_ERROR_PROTOCOL_FAULTY} = 157
${env:hestiaKERNEL_ERROR_PROTOCOL_EMPTY} = 158
${env:hestiaKERNEL_ERROR_PROTOCOL_UNSUPPORTED} = 159




# system (e.g. os interactable system)
${env:hestiaKERNEL_ERROR_SYSTEM_BAD_IO} = 160
${env:hestiaKERNEL_ERROR_SYSTEM_DEVICE_CROSS_LINK} = 161
${env:hestiaKERNEL_ERROR_SYSTEM_INTERRUPT_CALL} = 162
${env:hestiaKERNEL_ERROR_SYSTEM_INVALID} = 163
${env:hestiaKERNEL_ERROR_SYSTEM_MISSING_BLOCK_DEVICE} = 164
${env:hestiaKERNEL_ERROR_SYSTEM_MISSING_DEVICE} = 165
${env:hestiaKERNEL_ERROR_SYSTEM_MISSING_IO} = 166
${env:hestiaKERNEL_ERROR_SYSTEM_MISSING_PROCESS} = 167
${env:hestiaKERNEL_ERROR_SYSTEM_OUT_OF_DOMAIN} = 168
${env:hestiaKERNEL_ERROR_SYSTEM_OUT_OF_MEMORY} = 169
${env:hestiaKERNEL_ERROR_SYSTEM_OUT_OF_SPACE} = 170
${env:hestiaKERNEL_ERROR_SYSTEM_READ_ONLY_FILESYSTEM} = 171




# user
${env:hestiaKERNEL_ERROR_USER_ACCESS_BANNED} = 172
${env:hestiaKERNEL_ERROR_USER_ACCESS_LOCKED} = 173
${env:hestiaKERNEL_ERROR_USER_ACCESS_NOT_VERIFIED} = 174
${env:hestiaKERNEL_ERROR_USER_ACCESS_BAD} = 175
${env:hestiaKERNEL_ERROR_USER_ACCESS_REJECTED} = 176
${env:hestiaKERNEL_ERROR_USER_ACCESS_REVOKED} = 177
${env:hestiaKERNEL_ERROR_USER_ACCESS_EXISTS} = 178
${env:hestiaKERNEL_ERROR_USER_ACCESS_EMPTY} = 179
${env:hestiaKERNEL_ERROR_USER_ACCESS_MISSING} = 180
${env:hestiaKERNEL_ERROR_USER_ACCESS_INVALID} = 181
${env:hestiaKERNEL_ERROR_USER_ACCESS_EXPIRED} = 182
${env:hestiaKERNEL_ERROR_USER_ACCESS_MISMATCHED} = 183

${env:hestiaKERNEL_ERROR_USER_MFA_BANNED} = 184
${env:hestiaKERNEL_ERROR_USER_MFA_LOCKED} = 185
${env:hestiaKERNEL_ERROR_USER_MFA_NOT_VERIFIED} = 186
${env:hestiaKERNEL_ERROR_USER_MFA_BAD} = 188
${env:hestiaKERNEL_ERROR_USER_MFA_REJECTED} = 189
${env:hestiaKERNEL_ERROR_USER_MFA_REVOKED} = 190
${env:hestiaKERNEL_ERROR_USER_MFA_EXISTS} = 191
${env:hestiaKERNEL_ERROR_USER_MFA_EMPTY} = 192
${env:hestiaKERNEL_ERROR_USER_MFA_MISSING} = 193
${env:hestiaKERNEL_ERROR_USER_MFA_INVALID} = 194
${env:hestiaKERNEL_ERROR_USER_MFA_EXPIRED} = 195
${env:hestiaKERNEL_ERROR_USER_MFA_MISMATCHED} = 196

${env:hestiaKERNEL_ERROR_USER_ID_EXISTS} = 197
${env:hestiaKERNEL_ERROR_USER_ID_BANNED} = 198
${env:hestiaKERNEL_ERROR_USER_ID_BAD} = 199
${env:hestiaKERNEL_ERROR_USER_ID_LOCKED} = 200
${env:hestiaKERNEL_ERROR_USER_ID_NOT_VERIFIED} = 201
${env:hestiaKERNEL_ERROR_USER_ID_EMPTY} = 202
${env:hestiaKERNEL_ERROR_USER_ID_MISSING} = 203
${env:hestiaKERNEL_ERROR_USER_ID_INVALID} = 204
${env:hestiaKERNEL_ERROR_USER_ID_EXPIRED} = 205
${env:hestiaKERNEL_ERROR_USER_ID_MISMATCHED} = 206
${env:hestiaKERNEL_ERROR_USER_ID_DELETED} = 207
${env:hestiaKERNEL_ERROR_USER_PASSWORD_EXISTS} = 208
${env:hestiaKERNEL_ERROR_USER_PASSWORD_BANNED} = 209
${env:hestiaKERNEL_ERROR_USER_PASSWORD_BAD} = 210
${env:hestiaKERNEL_ERROR_USER_PASSWORD_REJECTED} = 211
${env:hestiaKERNEL_ERROR_USER_PASSWORD_REVOKED} = 212
${env:hestiaKERNEL_ERROR_USER_PASSWORD_EMPTY} = 213
${env:hestiaKERNEL_ERROR_USER_PASSWORD_MISSING} = 214
${env:hestiaKERNEL_ERROR_USER_PASSWORD_INVALID} = 215
${env:hestiaKERNEL_ERROR_USER_PASSWORD_EXPIRED} = 216
${env:hestiaKERNEL_ERROR_USER_PASSWORD_MISMATCHED} = 217
${env:hestiaKERNEL_ERROR_USER_KEY_EXISTS} = 218
${env:hestiaKERNEL_ERROR_USER_KEY_BANNED} = 219
${env:hestiaKERNEL_ERROR_USER_KEY_BAD} = 220
${env:hestiaKERNEL_ERROR_USER_KEY_REJECTED} = 221
${env:hestiaKERNEL_ERROR_USER_KEY_REVOKED} = 222
${env:hestiaKERNEL_ERROR_USER_KEY_EMPTY} = 223
${env:hestiaKERNEL_ERROR_USER_KEY_MISSING} = 224
${env:hestiaKERNEL_ERROR_USER_KEY_INVALID} = 225
${env:hestiaKERNEL_ERROR_USER_KEY_EXPIRED} = 226
${env:hestiaKERNEL_ERROR_USER_KEY_MISMATCHED} = 227
################################################################################
# Windows POWERSHELL Codes                                                     #
################################################################################
return
<#
RUN_AS_POWERSHELL




################################################################################
# Unix Main Codes                                                              #
################################################################################
# standard errors
hestiaKERNEL_ERROR_OK=0
hestiaKERNEL_ERROR_BAD_EXEC=1
hestiaKERNEL_ERROR_BAD_BUSY=2
hestiaKERNEL_ERROR_BAD_DESCRIPTOR=3
hestiaKERNEL_ERROR_BAD_EXCHANGE=4
hestiaKERNEL_ERROR_BAD_MOUNT=5
hestiaKERNEL_ERROR_BAD_PIPE=6
hestiaKERNEL_ERROR_BAD_REQUEST=7
hestiaKERNEL_ERROR_BAD_STREAM_PIPE=8
hestiaKERNEL_ERROR_PROCESS_IS_DEAD=9
hestiaKERNEL_ERROR_CANCELLED=10
hestiaKERNEL_ERROR_CLEANING_REQUIRED=11
hestiaKERNEL_ERROR_DEADLOCK=12
hestiaKERNEL_ERROR_EXPIRED=13
hestiaKERNEL_ERROR_ILLEGAL_BYTE_SEQUENCE=14
hestiaKERNEL_ERROR_ILLEGAL_SEEK=15
hestiaKERNEL_ERROR_INVALID_ARGUMENT=16
hestiaKERNEL_ERROR_IS_EMPTY=17
hestiaKERNEL_ERROR_MAXED_EXCHANGE=18
hestiaKERNEL_ERROR_MAXED_QUOTA=19
hestiaKERNEL_ERROR_MISSING_LOCK=20
hestiaKERNEL_ERROR_IS_NOT_EMPTY=21
hestiaKERNEL_ERROR_NOT_PERMITTED=22
hestiaKERNEL_ERROR_NOT_POSSIBLE=23
hestiaKERNEL_ERROR_NOT_POSSIBLE_BY_RFKILL=24
hestiaKERNEL_ERROR_NOT_RECOVERABLE=25
hestiaKERNEL_ERROR_OUT_OF_RANGE=26
hestiaKERNEL_ERROR_PERMISSION_DENIED=27
hestiaKERNEL_ERROR_TIMEOUT=28
hestiaKERNEL_ERROR_TOO_MANY_READ=29
hestiaKERNEL_ERROR_TOO_MANY_LOOP=30
hestiaKERNEL_ERROR_TOO_MANY_REFERENCES=31
hestiaKERNEL_ERROR_TOO_MANY_LINK=32
hestiaKERNEL_ERROR_TOO_MANY_OPENED=33
hestiaKERNEL_ERROR_TRY_AGAIN=34
hestiaKERNEL_ERROR_UNSUPPORTED=35
hestiaKERNEL_ERROR_WOULD_BLOCK=36




# lifecycle states
hestiaKERNEL_ERROR_RESTART=37
hestiaKERNEL_ERROR_RESUME=38
hestiaKERNEL_ERROR_SHUTDOWN=39
hestiaKERNEL_ERROR_SLEEP=40
hestiaKERNEL_ERROR_STALLED=41
hestiaKERNEL_ERROR_STANDBY=42
hestiaKERNEL_ERROR_UNRESPONSIVE=43
hestiaKERNEL_ERROR_TERMINATE=44
hestiaKERNEL_ERROR_PROGRESS_SCHEDULED=45
hestiaKERNEL_ERROR_PROGRESS_ALREADY_EXECUTING=46
hestiaKERNEL_ERROR_PROGRESS_EXECUTING=47
hestiaKERNEL_ERROR_PROGRESS_COMPLETED=48
hestiaKERNEL_ERROR_PROGRESS_UNRESPONSIVE=49
hestiaKERNEL_ERROR_PROGRESS_TERMINATE=50




# tri-tier inter-package communications
hestiaKERNEL_ERROR_LV1_NOT_SYNC=51
hestiaKERNEL_ERROR_LV1_PAUSED=52
hestiaKERNEL_ERROR_LV1_RESET=53
hestiaKERNEL_ERROR_LV2_NOT_SYNC=54
hestiaKERNEL_ERROR_LV2_PAUSED=55
hestiaKERNEL_ERROR_LV2_RESET=56
hestiaKERNEL_ERROR_LV3_NOT_SYNC=57
hestiaKERNEL_ERROR_LV3_PAUSED=58
hestiaKERNEL_ERROR_LV3_RESET=59




# data (input/output parameters type etc)
hestiaKERNEL_ERROR_DATA_BAD=60
hestiaKERNEL_ERROR_DATA_EMPTY=61
hestiaKERNEL_ERROR_DATA_INVALID=62
hestiaKERNEL_ERROR_DATA_IS_UNIQUE=63
hestiaKERNEL_ERROR_DATA_IS_NOT_UNIQUE=64
hestiaKERNEL_ERROR_DATA_BUSY=65
hestiaKERNEL_ERROR_DATA_DEAD=66
hestiaKERNEL_ERROR_DATA_EXISTS=67
hestiaKERNEL_ERROR_DATA_FAULTY=68
hestiaKERNEL_ERROR_DATA_MISSING=69
hestiaKERNEL_ERROR_DATA_OVERFLOW=70
hestiaKERNEL_ERROR_DATA_POISONED=71
hestiaKERNEL_ERROR_DATA_REMOVED=72
hestiaKERNEL_ERROR_DATA_TOO_BIG=73
hestiaKERNEL_ERROR_DATA_TOO_MANY_OPENED=74
hestiaKERNEL_ERROR_DATA_TOO_LONG=75
hestiaKERNEL_ERROR_DATA_MISMATCHED=76
hestiaKERNEL_ERROR_DATA_IS_NOT_DIRECTORY=77
hestiaKERNEL_ERROR_DATA_IS_NOT_FILE=78
hestiaKERNEL_ERROR_DATA_IS_NOT_LINK=79
hestiaKERNEL_ERROR_DATA_IS_NOT_SOCKET=80
hestiaKERNEL_ERROR_DATA_REMOTE_CHANGED=81
hestiaKERNEL_ERROR_DATA_REMOTE_ERROR=82
hestiaKERNEL_ERROR_DATA_REMOTE_IO=83
hestiaKERNEL_ERROR_DATA_MISSING_STREAMABLE_RESOURCES=84
hestiaKERNEL_ERROR_DATA_NOT_STREAMABLE=85




# entity (device file directory object etc)
hestiaKERNEL_ERROR_ENTITY_BAD=86
hestiaKERNEL_ERROR_ENTITY_EMPTY=87
hestiaKERNEL_ERROR_ENTITY_INVALID=88
hestiaKERNEL_ERROR_ENTITY_IS_UNIQUE=89
hestiaKERNEL_ERROR_ENTITY_IS_NOT_UNIQUE=90
hestiaKERNEL_ERROR_ENTITY_BUSY=91
hestiaKERNEL_ERROR_ENTITY_DEAD=92
hestiaKERNEL_ERROR_ENTITY_EXISTS=93
hestiaKERNEL_ERROR_ENTITY_FAULTY=94
hestiaKERNEL_ERROR_ENTITY_MISSING=95
hestiaKERNEL_ERROR_ENTITY_MISSING_CHILD=96
hestiaKERNEL_ERROR_ENTITY_OUT_OF_BUFFER=97
hestiaKERNEL_ERROR_ENTITY_POISONED=98
hestiaKERNEL_ERROR_ENTITY_REMOVED=99
hestiaKERNEL_ERROR_ENTITY_TOO_BIG=100
hestiaKERNEL_ERROR_ENTITY_TOO_MANY_OPENED=101
hestiaKERNEL_ERROR_ENTITY_UNATTACHED=102
hestiaKERNEL_ERROR_ENTITY_MISMATCHED=103
hestiaKERNEL_ERROR_ENTITY_IS_NOT_DIRECTORY=104
hestiaKERNEL_ERROR_ENTITY_IS_NOT_FILE=105
hestiaKERNEL_ERROR_ENTITY_IS_NOT_LINK=106
hestiaKERNEL_ERROR_ENTITY_IS_NOT_SOCKET=107
hestiaKERNEL_ERROR_ENTITY_REMOTE_CHANGED=108
hestiaKERNEL_ERROR_ENTITY_REMOTE_ERROR=109
hestiaKERNEL_ERROR_ENTITY_REMOTE_IO=110
hestiaKERNEL_ERROR_ENTITY_MISSING_STREAMABLE_RESOURCES=111
hestiaKERNEL_ERROR_ENTITY_NOT_STREAMABLE=112
hestiaKERNEL_ERROR_ENTITY_STREAMABLE=113
hestiaKERNEL_ERROR_ENTITY_A_TYPEWRITER=114
hestiaKERNEL_ERROR_ENTITY_NOT_A_TYPEWRITER=115
hestiaKERNEL_ERROR_ENTITY_BAD_DESCRIPTOR=116
hestiaKERNEL_ERROR_ENTITY_FILETABLE_OVERFLOW=117




# key (cryptography)
hestiaKERNEL_ERROR_KEY_BAD=118
hestiaKERNEL_ERROR_KEY_DESTROYED=119
hestiaKERNEL_ERROR_KEY_EXPIRED=120
hestiaKERNEL_ERROR_KEY_MISSING=121
hestiaKERNEL_ERROR_KEY_REJECTED=122
hestiaKERNEL_ERROR_KEY_REVOKED=123




# library
hestiaKERNEL_ERROR_LIBRARY_BAD=124
hestiaKERNEL_ERROR_LIBRARY_CORRUPTED=125
hestiaKERNEL_ERROR_LIBRARY_EXEC_FAILED=126
hestiaKERNEL_ERROR_LIBRARY_MAXED=127
hestiaKERNEL_ERROR_LIBRARY_MISSING=128




# network
hestiaKERNEL_ERROR_NETWORK_BAD=129
hestiaKERNEL_ERROR_NETWORK_BAD_AD=130
hestiaKERNEL_ERROR_NETWORK_DOWN=131
hestiaKERNEL_ERROR_NETWORK_NOT_CONNECTED=132
hestiaKERNEL_ERROR_NETWORK_RESET=133
hestiaKERNEL_ERROR_NETWORK_RFS=134
hestiaKERNEL_ERROR_NETWORK_UNREACHABLE=135

hestiaKERNEL_ERROR_NETWORK_HOST_DOWN=136
hestiaKERNEL_ERROR_NETWORK_HOST_UNREACHABLE=137
hestiaKERNEL_ERROR_NETWORK_SOCKET_UNSUPPORTED=138

hestiaKERNEL_ERROR_NETWORK_ADDRESS_IN_USE=139
hestiaKERNEL_ERROR_NETWORK_ADDRESS_UNAVAILABLE=140

hestiaKERNEL_ERROR_NETWORK_CONN_ABORTED=141
hestiaKERNEL_ERROR_NETWORK_CONN_IS_CONNECTED=142
hestiaKERNEL_ERROR_NETWORK_CONN_MISSING_DEST_ADDRESS=143
hestiaKERNEL_ERROR_NETWORK_CONN_MULTIHOP=144
hestiaKERNEL_ERROR_NETWORK_CONN_NOT_CONNECTED=145
hestiaKERNEL_ERROR_NETWORK_CONN_REFUSED=146
hestiaKERNEL_ERROR_NETWORK_CONN_RESET=147

hestiaKERNEL_ERROR_NETWORK_PAYLOAD_BAD=148
hestiaKERNEL_ERROR_NETWORK_PAYLOAD_EMPTY=149
hestiaKERNEL_ERROR_NETWORK_PAYLOAD_MISSING=150
hestiaKERNEL_ERROR_NETWORK_PAYLOAD_TOO_LONG=151




# protocol
hestiaKERNEL_ERROR_PROTOCOL_ADDRESS_UNSUPPORTED=152
hestiaKERNEL_ERROR_PROTOCOL_BAD=153
hestiaKERNEL_ERROR_PROTOCOL_FAMILY_UNSUPPORTED=154
hestiaKERNEL_ERROR_PROTOCOL_MISSING=155
hestiaKERNEL_ERROR_PROTOCOL_INVALID=156
hestiaKERNEL_ERROR_PROTOCOL_FAULTY=157
hestiaKERNEL_ERROR_PROTOCOL_EMPTY=158
hestiaKERNEL_ERROR_PROTOCOL_UNSUPPORTED=159




# system (e.g. os interactable system)
hestiaKERNEL_ERROR_SYSTEM_BAD_IO=160
hestiaKERNEL_ERROR_SYSTEM_DEVICE_CROSS_LINK=161
hestiaKERNEL_ERROR_SYSTEM_INTERRUPT_CALL=162
hestiaKERNEL_ERROR_SYSTEM_INVALID=163
hestiaKERNEL_ERROR_SYSTEM_MISSING_BLOCK_DEVICE=164
hestiaKERNEL_ERROR_SYSTEM_MISSING_DEVICE=165
hestiaKERNEL_ERROR_SYSTEM_MISSING_IO=166
hestiaKERNEL_ERROR_SYSTEM_MISSING_PROCESS=167
hestiaKERNEL_ERROR_SYSTEM_OUT_OF_DOMAIN=168
hestiaKERNEL_ERROR_SYSTEM_OUT_OF_MEMORY=169
hestiaKERNEL_ERROR_SYSTEM_OUT_OF_SPACE=170
hestiaKERNEL_ERROR_SYSTEM_READ_ONLY_FILESYSTEM=171




# user
hestiaKERNEL_ERROR_USER_ACCESS_BANNED=172
hestiaKERNEL_ERROR_USER_ACCESS_LOCKED=173
hestiaKERNEL_ERROR_USER_ACCESS_NOT_VERIFIED=174
hestiaKERNEL_ERROR_USER_ACCESS_BAD=175
hestiaKERNEL_ERROR_USER_ACCESS_REJECTED=176
hestiaKERNEL_ERROR_USER_ACCESS_REVOKED=177
hestiaKERNEL_ERROR_USER_ACCESS_EXISTS=178
hestiaKERNEL_ERROR_USER_ACCESS_EMPTY=179
hestiaKERNEL_ERROR_USER_ACCESS_MISSING=180
hestiaKERNEL_ERROR_USER_ACCESS_INVALID=181
hestiaKERNEL_ERROR_USER_ACCESS_EXPIRED=182
hestiaKERNEL_ERROR_USER_ACCESS_MISMATCHED=183

hestiaKERNEL_ERROR_USER_MFA_BANNED=184
hestiaKERNEL_ERROR_USER_MFA_LOCKED=185
hestiaKERNEL_ERROR_USER_MFA_NOT_VERIFIED=186
hestiaKERNEL_ERROR_USER_MFA_BAD=188
hestiaKERNEL_ERROR_USER_MFA_REJECTED=189
hestiaKERNEL_ERROR_USER_MFA_REVOKED=190
hestiaKERNEL_ERROR_USER_MFA_EXISTS=191
hestiaKERNEL_ERROR_USER_MFA_EMPTY=192
hestiaKERNEL_ERROR_USER_MFA_MISSING=193
hestiaKERNEL_ERROR_USER_MFA_INVALID=194
hestiaKERNEL_ERROR_USER_MFA_EXPIRED=195
hestiaKERNEL_ERROR_USER_MFA_MISMATCHED=196

hestiaKERNEL_ERROR_USER_ID_EXISTS=197
hestiaKERNEL_ERROR_USER_ID_BANNED=198
hestiaKERNEL_ERROR_USER_ID_BAD=199
hestiaKERNEL_ERROR_USER_ID_LOCKED=200
hestiaKERNEL_ERROR_USER_ID_NOT_VERIFIED=201
hestiaKERNEL_ERROR_USER_ID_EMPTY=202
hestiaKERNEL_ERROR_USER_ID_MISSING=203
hestiaKERNEL_ERROR_USER_ID_INVALID=204
hestiaKERNEL_ERROR_USER_ID_EXPIRED=205
hestiaKERNEL_ERROR_USER_ID_MISMATCHED=206
hestiaKERNEL_ERROR_USER_ID_DELETED=207

hestiaKERNEL_ERROR_USER_PASSWORD_EXISTS=208
hestiaKERNEL_ERROR_USER_PASSWORD_BANNED=209
hestiaKERNEL_ERROR_USER_PASSWORD_BAD=210
hestiaKERNEL_ERROR_USER_PASSWORD_REJECTED=211
hestiaKERNEL_ERROR_USER_PASSWORD_REVOKED=212
hestiaKERNEL_ERROR_USER_PASSWORD_EMPTY=213
hestiaKERNEL_ERROR_USER_PASSWORD_MISSING=214
hestiaKERNEL_ERROR_USER_PASSWORD_INVALID=215
hestiaKERNEL_ERROR_USER_PASSWORD_EXPIRED=216
hestiaKERNEL_ERROR_USER_PASSWORD_MISMATCHED=217

hestiaKERNEL_ERROR_USER_KEY_EXISTS=218
hestiaKERNEL_ERROR_USER_KEY_BANNED=219
hestiaKERNEL_ERROR_USER_KEY_BAD=220
hestiaKERNEL_ERROR_USER_KEY_REJECTED=221
hestiaKERNEL_ERROR_USER_KEY_REVOKED=222
hestiaKERNEL_ERROR_USER_KEY_EMPTY=223
hestiaKERNEL_ERROR_USER_KEY_MISSING=224
hestiaKERNEL_ERROR_USER_KEY_INVALID=225
hestiaKERNEL_ERROR_USER_KEY_EXPIRED=226
hestiaKERNEL_ERROR_USER_KEY_MISMATCHED=227
################################################################################
# Unix Main Codes                                                              #
################################################################################
return 0
#>
